import type { Category, CarBrand, Product, SellerProfile } from "./types";

export const categories: Category[] = [
  { id: "cat-1", name: "قطعات موتوری", slug: "engine-parts", icon: "⚙️", productCount: 1240 },
  { id: "cat-2", name: "سیستم ترمز", slug: "brake-system", icon: "🛑", productCount: 890 },
  { id: "cat-3", name: "قطعات بدنه", slug: "body-parts", icon: "🚗", productCount: 2100 },
  { id: "cat-4", name: "چراغ و روشنایی", slug: "lighting", icon: "💡", productCount: 650 },
  { id: "cat-5", name: "جلوبندی و تعلیق", slug: "suspension", icon: "🔧", productCount: 780 },
  { id: "cat-6", name: "لوازم برقی", slug: "electrical", icon: "⚡", productCount: 1100 },
  { id: "cat-7", name: "لاستیک و رینگ", slug: "tires-rims", icon: "🛞", productCount: 420 },
  { id: "cat-8", name: "فیلتر و صافی", slug: "filters", icon: "🔄", productCount: 960 },
  { id: "cat-9", name: "روغن و مایعات", slug: "oils-fluids", icon: "🛢️", productCount: 340 },
  { id: "cat-10", name: "لوازم جانبی", slug: "accessories", icon: "📱", productCount: 1500 },
  { id: "cat-11", name: "سیستم فرمان", slug: "steering", icon: "🎯", productCount: 520 },
  { id: "cat-12", name: "گیربکس و انتقال قدرت", slug: "transmission", icon: "⚙️", productCount: 680 },
];

export const subCategories: Record<string, Category[]> = {
  "engine-parts": [
    { id: "sub-1-1", name: "فیلتر روغن", slug: "oil-filter", parentId: "cat-1", productCount: 180 },
    { id: "sub-1-2", name: "فیلتر هوا", slug: "air-filter", parentId: "cat-1", productCount: 160 },
    { id: "sub-1-3", name: "شمع موتور", slug: "spark-plug", parentId: "cat-1", productCount: 120 },
    { id: "sub-1-4", name: "تسمه تایم", slug: "timing-belt", parentId: "cat-1", productCount: 90 },
    { id: "sub-1-5", name: "واتر پمپ", slug: "water-pump", parentId: "cat-1", productCount: 75 },
    { id: "sub-1-6", name: "رادیاتور", slug: "radiator", parentId: "cat-1", productCount: 110 },
  ],
  "brake-system": [
    { id: "sub-2-1", name: "لنت ترمز", slug: "brake-pad", parentId: "cat-2", productCount: 320 },
    { id: "sub-2-2", name: "دیسک ترمز", slug: "brake-disc", parentId: "cat-2", productCount: 250 },
    { id: "sub-2-3", name: "سیلندر ترمز", slug: "brake-cylinder", parentId: "cat-2", productCount: 140 },
    { id: "sub-2-4", name: "لاک ترمز", slug: "brake-fluid", parentId: "cat-2", productCount: 80 },
  ],
  "body-parts": [
    { id: "sub-3-1", name: "سپر", slug: "bumper", parentId: "cat-3", productCount: 420 },
    { id: "sub-3-2", name: "گلگیر", slug: "fender", parentId: "cat-3", productCount: 310 },
    { id: "sub-3-3", name: "درب جانبی", slug: "door", parentId: "cat-3", productCount: 280 },
    { id: "sub-3-4", name: "آینه بغل", slug: "side-mirror", parentId: "cat-3", productCount: 190 },
    { id: "sub-3-5", name: "جلوپنجره", slug: "grille", parentId: "cat-3", productCount: 150 },
    { id: "sub-3-6", name: "کاپوت", slug: "hood", parentId: "cat-3", productCount: 120 },
  ],
  "lighting": [
    { id: "sub-4-1", name: "چراغ جلو", slug: "headlight", parentId: "cat-4", productCount: 200 },
    { id: "sub-4-2", name: "چراغ عقب", slug: "taillight", parentId: "cat-4", productCount: 180 },
    { id: "sub-4-3", name: "دیلایت", slug: "daytime-light", parentId: "cat-4", productCount: 120 },
    { id: "sub-4-4", name: "مه شکن", slug: "fog-light", parentId: "cat-4", productCount: 90 },
  ],
  "suspension": [
    { id: "sub-5-1", name: "کمک فنر", slug: "shock-absorber", parentId: "cat-5", productCount: 200 },
    { id: "sub-5-2", name: "طبق", slug: "control-arm", parentId: "cat-5", productCount: 150 },
    { id: "sub-5-3", name: "سیبک", slug: "ball-joint", parentId: "cat-5", productCount: 130 },
    { id: "sub-5-4", name: "میل تعادل", slug: "sway-bar", parentId: "cat-5", productCount: 100 },
  ],
};

export const carBrands: CarBrand[] = [
  { id: "brand-1", name: "پژو", slug: "peugeot", country: "فرانسه", modelCount: 12 },
  { id: "brand-2", name: "ایران خودرو", slug: "ikco", country: "ایران", modelCount: 15 },
  { id: "brand-3", name: "سایپا", slug: "saipa", country: "ایران", modelCount: 10 },
  { id: "brand-4", name: "تویوتا", slug: "toyota", country: "ژاپن", modelCount: 20 },
  { id: "brand-5", name: "هیوندای", slug: "hyundai", country: "کره جنوبی", modelCount: 14 },
  { id: "brand-6", name: "کیا", slug: "kia", country: "کره جنوبی", modelCount: 12 },
  { id: "brand-7", name: "MVM", slug: "mvm", country: "چین", modelCount: 8 },
  { id: "brand-8", name: "چری", slug: "chery", country: "چین", modelCount: 6 },
  { id: "brand-9", name: "فوتون", slug: "foton", country: "چین", modelCount: 5 },
  { id: "brand-10", name: "KMC", slug: "kmc", country: "ایران", modelCount: 7 },
];

const sellers: SellerProfile[] = [
  { id: "seller-1", shopName: "قطعات یدکی پارسیان", rating: 4.8, totalSales: 1250, verified: true, city: "تهران" },
  { id: "seller-2", shopName: "فروشگاه آنلاین راد", rating: 4.6, totalSales: 890, verified: true, city: "اصفهان" },
  { id: "seller-3", shopName: "یدک مارکت", rating: 4.9, totalSales: 2100, verified: true, city: "تهران" },
  { id: "seller-4", shopName: "قطعات خودرو کارگاه", rating: 4.3, totalSales: 450, verified: false, city: "مشهد" },
  { id: "seller-5", shopName: "پارستیدک", rating: 4.7, totalSales: 1680, verified: true, city: "تبریز" },
];

export const products: Product[] = [
  {
    id: "prod-1",
    title: "لنت ترمز جلو پراید امکو",
    slug: "prayad-front-brake-pad-omco",
    description: "لنت ترمز جلو خودرو پراید برند امکو با کیفیت بالا و عمر طولانی. مناسب برای پراید ۱۳۱، ۱۳۲، ۱۱۱ و سایر مدل‌ها.",
    price: 1245000,
    originalPrice: 1450000,
    currency: "IRR",
    condition: "NEW",
    brand: "امکو",
    origin: "ایران",
    warranty: "۶ ماه",
    category: categories[1],
    seller: sellers[0],
    stock: 45,
    salesCount: 320,
    rating: 4.5,
    reviewCount: 89,
    featured: true,
    images: [
      { id: "img-1-1", url: "/placeholder/brake-pad-1.jpg", alt: "لنت ترمز جلو پراید", primary: true },
      { id: "img-1-2", url: "/placeholder/brake-pad-2.jpg", alt: "لنت ترمز جلو پراید - نمای جانبی", primary: false },
    ],
    compatibleCars: [
      { carModel: { id: "m-1", name: "پراید ۱۳۱", slug: "pride-131", brand: carBrands[2], yearStart: 2005, yearEnd: 2024 }, yearFrom: 2005, yearTo: 2024 },
      { carModel: { id: "m-2", name: "پراید ۱۱۱", slug: "pride-111", brand: carBrands[2], yearStart: 2008, yearEnd: 2024 }, yearFrom: 2008, yearTo: 2024 },
    ],
    createdAt: new Date("2025-01-15"),
  },
  {
    id: "prod-2",
    title: "باتری خودرو صبا باتری واریان ۶۰ آمپر",
    slug: "saba-battery-variant-60ah",
    description: "باتری خودرو صبا باتری مدل واریان با ظرفیت ۶۰ آمپر ساعت. مناسب برای خودروهای پراید، تیبا، ساینا و ۲۰۶.",
    price: 4174000,
    currency: "IRR",
    condition: "NEW",
    brand: "صبا باتری",
    origin: "ایران",
    warranty: "۱۸ ماه",
    category: categories[5],
    seller: sellers[2],
    stock: 30,
    salesCount: 890,
    rating: 4.7,
    reviewCount: 234,
    featured: true,
    images: [
      { id: "img-2-1", url: "/placeholder/battery-1.jpg", alt: "باتری صبا واریان", primary: true },
    ],
    createdAt: new Date("2025-02-10"),
  },
  {
    id: "prod-3",
    title: "لاستیک بارز مدل P648 سایز ۱۸۵/۶۵R۱۴ چهارفصل",
    slug: "barez-p648-185-65r14",
    description: "لاستیک خودرو بارز مدل P648 با سایز ۱۸۵/۶۵R۱۴ چهار فصل. مناسب برای پژو ۲۰۶، پارس و سمند.",
    price: 7950000,
    originalPrice: 8500000,
    currency: "IRR",
    condition: "NEW",
    brand: "بارز",
    origin: "ایران",
    warranty: "۴۸ ماه",
    category: categories[6],
    seller: sellers[0],
    stock: 15,
    salesCount: 450,
    rating: 4.6,
    reviewCount: 178,
    featured: true,
    images: [
      { id: "img-3-1", url: "/placeholder/tire-1.jpg", alt: "لاستیک بارز", primary: true },
    ],
    compatibleCars: [
      { carModel: { id: "m-3", name: "پژو ۲۰۶", slug: "peugeot-206", brand: carBrands[0], yearStart: 2001, yearEnd: 2024 }, yearFrom: 2001, yearTo: 2024 },
      { carModel: { id: "m-4", name: "سمند", slug: "samand", brand: carBrands[1], yearStart: 2002, yearEnd: 2024 }, yearFrom: 2002, yearTo: 2024 },
    ],
    createdAt: new Date("2025-03-05"),
  },
  {
    id: "prod-4",
    title: "دیسک و صفحه پراید والئو",
    slug: "pride-clutch-disc-valeo",
    description: "دیسک و صفحه کلاچ پراید برند والئو اصل فرانسه. مناسب برای تمامی مدل‌های پراید.",
    price: 8200000,
    currency: "IRR",
    condition: "NEW",
    brand: "والئو",
    origin: "فرانسه",
    warranty: "۱۲ ماه",
    category: categories[11],
    seller: sellers[1],
    stock: 22,
    salesCount: 670,
    rating: 4.8,
    reviewCount: 156,
    featured: true,
    images: [
      { id: "img-4-1", url: "/placeholder/clutch-1.jpg", alt: "دیسک و صفحه پراید", primary: true },
    ],
    createdAt: new Date("2025-01-20"),
  },
  {
    id: "prod-5",
    title: "هدلایت M8 Pro کانکس پایه H1",
    slug: "headlight-m8-pro-h1",
    description: "هدلایت LED مدل M8 Pro با شدت نور ۱۲۰۰۰۰ لومن. نصب آسان بدون نیاز به تغییر سیم‌کشی.",
    price: 1840000,
    currency: "IRR",
    condition: "NEW",
    brand: "کانکس",
    origin: "چین",
    warranty: "۱۲ ماه",
    category: categories[3],
    seller: sellers[2],
    stock: 80,
    salesCount: 1200,
    rating: 4.4,
    reviewCount: 310,
    featured: true,
    images: [
      { id: "img-5-1", url: "/placeholder/headlight-1.jpg", alt: "هدلایت M8 Pro", primary: true },
    ],
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "prod-6",
    title: "فیلتر روغن پراید فیکس",
    slug: "pride-oil-filter-fix",
    description: "فیلتر روغن خودرو پراید برند فیکس. تصفیه عالی روغن موتور و افزایش عمر موتور.",
    price: 320000,
    originalPrice: 380000,
    currency: "IRR",
    condition: "NEW",
    brand: "فیکس",
    origin: "ایران",
    warranty: "۶ ماه",
    category: categories[7],
    seller: sellers[0],
    stock: 200,
    salesCount: 2100,
    rating: 4.3,
    reviewCount: 420,
    featured: false,
    images: [
      { id: "img-6-1", url: "/placeholder/filter-1.jpg", alt: "فیلتر روغن پراید", primary: true },
    ],
    createdAt: new Date("2025-02-15"),
  },
  {
    id: "prod-7",
    title: "کمک فنر جلو سمند",
    slug: "samand-front-shock-absorber",
    description: "کمک فنر جلو خودرو سمند مناسب برای سمند LX و EF7. کیفیت بالا و نصب آسان.",
    price: 1850000,
    currency: "IRR",
    condition: "NEW",
    brand: "کاییان",
    origin: "ایران",
    warranty: "۱۲ ماه",
    category: categories[4],
    seller: sellers[3],
    stock: 35,
    salesCount: 280,
    rating: 4.5,
    reviewCount: 67,
    featured: false,
    images: [
      { id: "img-7-1", url: "/placeholder/shock-1.jpg", alt: "کمک فنر جلو سمند", primary: true },
    ],
    compatibleCars: [
      { carModel: { id: "m-4", name: "سمند", slug: "samand", brand: carBrands[1], yearStart: 2002, yearEnd: 2024 }, yearFrom: 2002, yearTo: 2024 },
    ],
    createdAt: new Date("2025-03-10"),
  },
  {
    id: "prod-8",
    title: "روغن موتور بهران ۱۰W-40 حجم ۴ لیتر",
    slug: "bahrain-engine-oil-10w40-4l",
    description: "روغن موتور بهران با گرانروی ۱۰W-40 و حجم ۴ لیتر. مناسب برای اکثر خودروهای سواری.",
    price: 680000,
    currency: "IRR",
    condition: "NEW",
    brand: "بهران",
    origin: "ایران",
    warranty: "اصالت کالا",
    category: categories[8],
    seller: sellers[2],
    stock: 100,
    salesCount: 1800,
    rating: 4.6,
    reviewCount: 530,
    featured: false,
    images: [
      { id: "img-8-1", url: "/placeholder/oil-1.jpg", alt: "روغن موتور بهران", primary: true },
    ],
    createdAt: new Date("2025-01-25"),
  },
  {
    id: "prod-9",
    title: "سپر جلو پژو ۲۰۶",
    slug: "peugeot-206-front-bumper",
    description: "سپر جلو خودرو پژو ۲۰۶ رنگ مشکی. ساخته شده از پلاستیک ABS با کیفیت بالا.",
    price: 3200000,
    currency: "IRR",
    condition: "NEW",
    brand: " aftermarket",
    origin: "ایران",
    warranty: "۳ ماه",
    category: categories[2],
    seller: sellers[4],
    stock: 12,
    salesCount: 180,
    rating: 4.2,
    reviewCount: 45,
    featured: false,
    images: [
      { id: "img-9-1", url: "/placeholder/bumper-1.jpg", alt: "سپر جلو پژو ۲۰۶", primary: true },
    ],
    compatibleCars: [
      { carModel: { id: "m-3", name: "پژو ۲۰۶", slug: "peugeot-206", brand: carBrands[0], yearStart: 2001, yearEnd: 2024 }, yearFrom: 2001, yearTo: 2024 },
    ],
    createdAt: new Date("2025-04-05"),
  },
  {
    id: "prod-10",
    title: "لاستیک کویرتایر مدل KB26 سایز ۱۶۵/۶۵R۱۳ چهارفصل",
    slug: "kavir-tire-kb26-165-65r13",
    description: "لاستیک خودرو کویرتایر مدل KB26 سایز ۱۶۵/۶۵R۱۳ چهار فصل. مناسب برای پراید.",
    price: 5425000,
    currency: "IRR",
    condition: "NEW",
    brand: "کویر تایر",
    origin: "ایران",
    warranty: "۴۸ ماه",
    category: categories[6],
    seller: sellers[1],
    stock: 20,
    salesCount: 340,
    rating: 4.4,
    reviewCount: 98,
    featured: false,
    images: [
      { id: "img-10-1", url: "/placeholder/tire-2.jpg", alt: "لاستیک کویرتایر", primary: true },
    ],
    compatibleCars: [
      { carModel: { id: "m-1", name: "پراید ۱۳۱", slug: "pride-131", brand: carBrands[2], yearStart: 2005, yearEnd: 2024 }, yearFrom: 2005, yearTo: 2024 },
    ],
    createdAt: new Date("2025-03-20"),
  },
  {
    id: "prod-11",
    title: "شمع پراید NGK",
    slug: "pride-spark-plug-ngk",
    description: "شمع خودرو پراید برند NGK ژاپن. احتراق بهتر و کاهش مصرف سوخت.",
    price: 180000,
    currency: "IRR",
    condition: "NEW",
    brand: "NGK",
    origin: "ژاپن",
    warranty: "۶ ماه",
    category: categories[0],
    seller: sellers[0],
    stock: 150,
    salesCount: 2400,
    rating: 4.7,
    reviewCount: 560,
    featured: false,
    images: [
      { id: "img-11-1", url: "/placeholder/spark-plug-1.jpg", alt: "شمع NGK پراید", primary: true },
    ],
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "prod-12",
    title: "رادیاتور آب پژو ۴۰۵",
    slug: "peugeot-405-water-radiator",
    description: "رادیاتور آب خودرو پژو ۴۰۵. خنک‌کاری عالی موتور با جنس آلومینیوم اصل.",
    price: 2900000,
    originalPrice: 3200000,
    currency: "IRR",
    condition: "NEW",
    brand: "تکنو",
    origin: "ایران",
    warranty: "۱۲ ماه",
    category: categories[0],
    seller: sellers[2],
    stock: 18,
    salesCount: 420,
    rating: 4.5,
    reviewCount: 110,
    featured: false,
    images: [
      { id: "img-12-1", url: "/placeholder/radiator-1.jpg", alt: "رادیاتور آب پژو ۴۰۵", primary: true },
    ],
    compatibleCars: [
      { carModel: { id: "m-5", name: "پژو ۴۰۵", slug: "peugeot-405", brand: carBrands[0], yearStart: 1995, yearEnd: 2024 }, yearFrom: 1995, yearTo: 2024 },
    ],
    createdAt: new Date("2025-01-30"),
  },
];

export const cities = [
  "تهران", "اصفهان", "مشهد", "تبریز", "شیراز", "کرج", "اهواز", "قم",
  "سلمان شهر", "کرمان", "یزد", "اراک", "بندرعباس", "زنجان", "همدان",
  "سنندج", "بیرجند", "بوشهر", "بجنورد", "چالوس", "رشت", "ساری",
];

export const plaqueLetters = ["ب", "پ", "ت", "ث", "ج", "چ", "ح", "خ", "د", "ذ", "ر", "ز", "ژ", "س", "ش", "ص", "ض", "ط", "ظ", "ع", "غ", "ف", "ق", "ک", "گ", "ل", "م", "ن", "و", "ه", "ی"];

export const conditions = [
  { value: "NEW", label: "نو" },
  { value: "USED", label: "کارکرده" },
  { value: "REFURBISHED", label: "بازسازی شده" },
];

export const priceRanges = [
  { label: "زیر ۵۰۰ هزار تومان", min: 0, max: 500000 },
  { label: "۵۰۰ هزار تا ۱ میلیون", min: 500000, max: 1000000 },
  { label: "۱ تا ۳ میلیون", min: 1000000, max: 3000000 },
  { label: "۳ تا ۵ میلیون", min: 3000000, max: 5000000 },
  { label: "۵ تا ۱۰ میلیون", min: 5000000, max: 10000000 },
  { label: "بالای ۱۰ میلیون", min: 10000000, max: undefined },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("fa-IR").format(price) + " تومان";
}

export function formatPriceShort(price: number): string {
  if (price >= 1000000) {
    return (price / 1000000).toFixed(1).replace(".0", "") + " میلیون";
  }
  if (price >= 1000) {
    return (price / 1000).toFixed(0) + " هزار";
  }
  return price.toString();
}

export function getDiscountPercent(price: number, originalPrice?: number): number | null {
  if (!originalPrice || originalPrice <= price) return null;
  return Math.round(((originalPrice - price) / originalPrice) * 100);
}
